# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    
env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE:  ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}
  BOT_NAME: "bot-new"
  JAR_PATH: "build/libs/discord_bot-1.0-SNAPSHOT-all.jar"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: |-
        chmod +x gradlew
    - name: Build with Gradle
      run: |-
        ./gradlew build
    - name: create shadow jar
      run: |- 
        ./gradlew shadowJar
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: build/libs/discord_bot-1.0-SNAPSHOT-all.jar
      
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: load CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}
#     - name: clean up cloud files
#       run: |- 
#         gcloud compute ssh "$GCE_INSTANCE" \
#             --zone="$GCE_INSTANCE_ZONE" \
#             --command="cd .. && cd andrewlinington9/" && tmux ls && sudo rm discord_bot-1.0-SNAPSHOT-all.jar &&  tmux kill-session -t bot
    - name: retrieve build artifacts
      uses: actions/download-artifact@v2
      with:
        name: jar
    - name: list files
      run: |-
        ls -R
    - name: upload cloud files
      run: |-
        gcloud compute scp ~/work/DiscordBot/DiscordBot/discord_bot-1.0-SNAPSHOT-all.jar bot-new:~ --zone "$GCE_INSTANCE_ZONE"
    - name: Deploy new JAR
      run: |- 
          gcloud compute ssh "$GCE_INSTANCE" \
            --zone="$GCE_INSTANCE_ZONE" \
            --command="mv discord_bot-1.0-SNAPSHOT-all.jar ../andrewlinington9/ && echo completed moving object && cd ../andrewlinington9/ &&  echo pre tmux &&  tmux new -s bot -d && echo post tmux &&  java -jar discord_bot-1.0-SNAPSHOT-all.jar"
    
